### PR TITLE
Add device sleep action

### PR DESCRIPTION
**Pull request by muesli**
Based on #58 by @henryso: Add a special `device` action that lets you put the device into sleep mode until the next key-event arrives.

Closes #58.

### CODE REVIEW

**Comment by henryso** [comment]
@muesli There is one thing that didn't make it through.  In the sleep action, in addition to dimming the Stream Deck, my code also blanked the buttons and restored them on waking.  If you are amenable to it, should I re-implement it by wrapping the device as I did before or do you want this done some other way?  If you are against it, would it be OK to implement it as optional (e.g., controlled by a command line option)?

Second, if I set `device = "sleep"` on action_hold, the device wakes up as soon as I release the button.  I'll see if I can figure out how to fix that.

**Comment by muesli** [comment]
> @muesli There is one thing that didn't make it through. In the sleep action, in addition to dimming the Stream Deck, my code also blanked the buttons and restored them on waking.

Does this make a difference? What's your use-case for this?

> Second, if I set `device = "sleep"` on action_hold, the device wakes up as soon as I release the button. I'll see if I can figure out how to fix that.

Sorry about that. If you can't figure it out, please make sure to open a ticket!

**Comment by henryso** [comment]
@muesli I would like all the buttons to blank in sleep mode so that the room is completely dark when the device is "sleeping".  I guess it's aesthetic preference, but that's my use-case.

**Comment by muesli** [comment]
> @muesli I would like all the buttons to blank in sleep mode so that the room is completely dark when the device is "sleeping". I guess it's aesthetic preference, but that's my use-case.

The `Sleep` call sets the brightness to 0 which makes the buttons appear completely dark for me. Are you experiencing something different?

**Comment by henryso** [comment]
Yes. On my device (Stream Deck XL), the buttons get dim but you can still see them.

**Comment by muesli** [comment]
Ok, that's a bit annoying and I guess you're right, we'll have to work around this. We shouldn't do this in `deckmaster` however: that's something that should be fixed in the `streamdeck` dependency, https://github.com/muesli/streamdeck.

**Comment by henryso** [comment]
I think the action_hold issue will need to be fixed there as well.  Maybe button releases while the device is "sleeping" can simply not wake it.

**Pull request merged**
