### PR TITLE
Time widget

### PR DESCRIPTION
**Pull request by zMoooooritz**
These changes add a new mode attribute to the clock widget. This allows for a hour/min/sec widget per button. Therefore the clock can be spread over three buttons for better readability.

### CODE REVIEW

**Comment by muesli** [comment]
This is a great idea, but maybe we could even improve it more. I'm sure some people would prefer to only see hour & minute, ignoring the seconds for example. So maybe we make the mode composable (like `hour,minute`) and dynamically layout the content in the available space.

What do you think?

**Comment by muesli** [comment]
Thinking about it some more, maybe we should actually use time format strings: https://golang.org/pkg/time/#Time.Format

**Comment by zMoooooritz** [comment]
Yes this sounds good to allow some more customization for users that dont modify the sourcecode.
This would probably also allow us to merge the date and clock widgets.
We should therefore rename and use the mode attribute more like a format attribute.
How would you want the format string to be layed out? Since using formats like ANSIC would result in difficulties splitting the string at the intended positions.
Maybe some kind of semicolon separated string that is allowed to contain all values defined in the second const block in [https://golang.org/src/time/format.go](time/format.go) and then cap the maximum number of fields to 3?

**Comment by muesli** [comment]
We could either split by `\n` or, as you suggested, a semicolon (maybe less confusing to the average user).

Good point about the font attributes, I hadn't considered that yet. I guess we would have to introduce a separate `font` config field for this widget, and provide a few defaults (`regular`, `bold`, `thin`).

Some more food for thought: Go's time formatting is also a bit obscure (to the average user), maybe we should provide a few common alternatives here:

```go
const  (
	yyyy = "2006"
	yy = "06"
	mmmm = "January"
	mmm = "Jan"
	mm = "01"
	dddd = "Monday"
	ddd = "Mon"
	dd = "02"

	HHT = "03"
	HH = "15"
	MM = "04"
	SS = "05"
	ss = "05"
	tt = "PM"
	Z = "MST"
	ZZZ = "MST"
	o = "Z07:00"
)
```

We could also look into using https://github.com/vjeantet/jodaTime.

**Comment by zMoooooritz** [comment]
I have implemented our thought into a new widget (time).
The mapToTimeString method is relative elongated and could probably be done better in go?!
One thing we should think about is whether or not we should already fully remove the clock and date widget since this results in segfaults with old .deck files that use these widgets.

**Comment by muesli** [comment]
> I have implemented our thought into a new widget (time).

Awesome!

> The mapToTimeString method is relative elongated and could probably be done better in go?!

If you don't mind I'll give it a shot and push to your branch.

> One thing we should think about is whether or not we should already fully remove the clock and date widget since this results in segfaults with old .deck files that use these widgets.

Good point! We could remove the old widgets, but leave shortcuts for `date` and `clock` widgets, that set up the new `time` widget with a configuration that matches the previous widgets' looks.

**Comment by zMoooooritz** [comment]
>If you don't mind I'll give it a shot and push to your branch.

Yes sure go ahead since that is the best I can think of rn

> Good point! We could remove the old widgets, but leave shortcuts for `date` and `clock` widgets, that set up the new `time` widget with a configuration that matches the previous widgets' looks.

I have now added these fallback shortcuts altough I'm not a huge fan of the resulting code duplication this is probably the best way to do it. The example main.deck contains the new time widget with the custom config to make people use it the way they want it.
On a side note we should therefore add some documentation for the time widget.

**Comment by muesli** [comment]
> On a side note we should therefore add some documentation for the time widget.

We should indeed add documentation about the available widgets and their configuration options!

**Pull request merged**
